### ISSUE TITLE
configure fixed IP?

### ISSUE THREAD

**Issue by JotWee** [nfarina/homebridge-sonos#11]
I have a SONOS 5.1 setup with a playbar. In order to work, homebridge needs to use the ip of the playbar, not one of the other speakers. What can be done?

**Comment by fwboettger** [comment]
@JotWee - did you install or update to version 0.0.3? This should discover the "coordinator" device (i.e. the Playbar) of your 5.1 setup.

**Comment by JotWee** [comment]
oops, of course i didn't...
Problem solved, thx a lot!
