### ISSUE TITLE
Dynamic device grouping (Sonos mobile or Desktop app) and on-the-fly update of registered accessories with homebridge-sonos

### ISSUE THREAD

**Issue by fwboettger** [nfarina/homebridge-sonos#12]
@nfarina - i'm now going to look into the plugin implementation enhancement to register to topology change events (nodes-sonos listener functionality) and to react to it accordingly. As far as i understand the general homebridge plugin and the specific sonos plugin implementation, one would need to de-register ("unbind"?) previously discovered devices as per the "SonosAccessory.prototype.search" function and to re-discover and correspondingly re-register ("bind"?) appropriate devices in case of certain topology changes.
Question: how to best achieve this de-registering/unbinding of affected previously discovered devices?

**Comment by nfarina** [comment]
This is not currently possible with homebridge. Services/Accessories cannot be changed after the plugin first initializes.

**Comment by fwboettger** [comment]
@nfarina - thanks much (also for fixing my mistake with the missing reference to the underscore package, apologies for that).
Is it possible to change an accessories' "this.device" member during runtime? If yes, this would probably the solution then, if not then i don't have an idea how to possibly handle such dynamic group management changes....

**Comment by nfarina** [comment]
You can certainly change what devices you're speaking with "behind the scenes" at any time - but when HomeKit discovers an Accessory, that accessory's details shouldn't change at runtime.

**Comment by fwboettger** [comment]
Thanks much for confirmation, this is perfect then and the way to go :-)

**Comment by fwboettger** [comment]
Thanks
