### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by montogeek** [nfarina/homebridge-sonos#28]
Hi

I am trying to install this plugin, I am using Insteon+ app to add Homebridge device, Insteon+ sets Siri control name to "Homebridge".

My config file:

``` js
{
  "accessories": [
    {
      "accessory": "Sonos",
      "name": "Hallway Speakers",
      "room": "Hallway"
    }
  ]
}
```

homebridge log

``` bash
👉  homebridge --debug
[6/14/2016, 8:44:57 PM] Loaded plugin: homebridge-sonos
[6/14/2016, 8:44:57 PM] Registering accessory 'homebridge-sonos.Sonos'
[6/14/2016, 8:44:57 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[6/14/2016, 8:44:57 PM] Homebridge is running on port 51826.
```

"Hallway Speakers" is the name in the Sonos app too.

Still, when I say to Siri: "Siri, turn on the Hallway Speakers" it says that is beyond its abilities.

What I am doing wrong?

Thanks!

**Comment by grzegorzkazulak** [comment]
@montogeek The name of the speaker in Sonos should be set to Hallway, not Hallway Speakers.

**Comment by montogeek** [comment]
Thanks @grzegorzkazulak !
