### ISSUE TITLE
takes 98% CPU - Sonos not responding anymore

### ISSUE THREAD

**Issue by frogstar** [nfarina/homebridge-sonos#40]
I have tested on a Raspberry 1 B and on a Raspberry 2 B.

After installing homebridge verything looks good, until i install the homebridge-sonos plugin and add any sonos-speoker to the config-json. 
Atter this change the homebridge does still start without error, but it becomes unresponsive. The new Speaker are also now showing in HomeKit. 

Looking into TOP i can see that homebridge is constantly using 98 % CPU
Also as long as homebridge-sonos is running in homebridge, the whole Sonos System becomes unresponsive. I need to stop hiomebridge in order to be able to start/stop any Sonos player.

Any advice what i could do to get it so work? 

PS: there is nothing else installed. Only homebridge and homberidge-sonos.

**Comment by fwboettger** [comment]
Can you please try with the new plugin version (see also merged pull request #39 ). This is using a version of the sonos lib that's supposedly coming with an improved sonos speaker discovery implementation, might be a solution to your case....

**Comment by frogstar** [comment]
Hi, i tested it and it is still at 98% CPU. But maybe i didnt "update" ist correct? What i did was to invoke this command
`sudo npm - g install homebridge-sonos`

My understanding is that this will install the latest Version - correct?

**Comment by misanthrophy** [comment]
otherwise try: `sudo npm -g update homebridge-sonos`

**Comment by frogstar** [comment]
i tried that as well. If i look for the Version, it appear that i am running the latest Version.

Is there any way how i could figure out whats wrong and why it is not working for me? Should it work on a Raspberry 1 or do i just wait till i get the other raspberry delivered and test on raspberry 2?

**Comment by frogstar** [comment]
So, even though i didn't get it to work on the old raspberry, it is working now in a virtual machine with ubuntu lts 14. I will keep it that way for now. Used the fork of homebridge-sonos which allows to change the volume. works well so far.
Thanks for your support
