### ISSUE TITLE
No volume control - with Fork (dominicstelljes/homebridge-sonos)

### ISSUE THREAD

**Issue by farberm** [nfarina/homebridge-sonos#45]
I installed the fork into node_modules/homebridge-sonos using git clone command

I have tried several commands to control the volume however Siri says does not understand

Hey Siri - set Living Room Speaker Volume to 30 percent
Hey Siri, set living room speaker brightness to 30

No matter what the combination the answer is always that Siri does not understand. Any help would be appreciated

**Comment by farberm** [comment]
Fixed - install location shuld be usr/local/lib/node_modules. Was inwrong directory when installing

**Comment by dominicstelljes** [comment]
Sorry for the very late reply. Im sorry that you have got problems. So it works fine now?
