### ISSUE TITLE
No Volume Slider (fork-dominicstelljes/homebridge-sonos)

### ISSUE THREAD

**Issue by john2691** [nfarina/homebridge-sonos#52]
I saw a similar issue posted but the fix didn't work. (See here for previous issue https://github.com/nfarina/homebridge-sonos/issues/45)

I get a switch, but no slider for volume control. Siri also says she can't control brightness (volume) for that accessory.

**Comment by dominicstelljes** [comment]
Hey,

maybe you have got the wrong version and not mine? Im using my version and its running fine. sorry for the late reply.

**Comment by john2691** [comment]
No worries, I believe I'm running the fork, how would I make sure? What's the proper npm install command?

**Comment by john2691** [comment]
Fixed, I reinstalled homebridge and the forked repo, all seems to be working.

**Comment by dominicstelljes** [comment]
Okay, have fun with this fork. ;)
