### ISSUE TITLE
Ignore TV Input 

### ISSUE THREAD

**Issue by thevisualist** [nfarina/homebridge-sonos#79]
Hi, I‘m using the plugin to turn the music off on all speakers when I leave the house. I experienced some issue with the TV autoplay of my Sonos Amp. The playback is not supposed to be stopped (except the 10 min timeout) so turning it off will fail and my scene will also fail to execute properly.
Is there a possibility to ignore the TV input within the plugin? So that it only switches to an on state when actual music is playing?

Thanks in advance.

PS: I implemented this feature in my setup using IFTTT via Webhook in the past but I want to get rid of the cloud dependency.

**Comment by JohnathonMohr** [comment]
Can you describe your scenario a little more specifically?  Are other speakers grouped with the Amp?  Is the Amp part of the scene?  What's the full setup, what happens now, and how would you like it to change?

**Comment by JohnathonMohr** [comment]
Do note though that I don't have an Amp to test with, and I don't know what @nfarina has, so there could be limits to how much help we can give.
